// Registrable domains from the bundled Public Suffix List: the part of a hostname one organisation (or one
// customer of a shared host) controls.

const IPV4 = /^\d{1,3}(?:\.\d{1,3}){3}$/;

/**
 * @typedef {object} PublicSuffixes  as generated by tools/update-data.mjs
 * @property {string[]} icann
 * @property {string[]} private
 */

/**
 * @typedef {object} SuffixIndex
 * @property {Set<string>} rules
 * @property {Set<string>} wildcards  parents of "*." rules
 * @property {Set<string>} exceptions
 * @property {Set<string>} privateRules  the PRIVATE section's rules, prefix kept ("!x", "*.x", "x")
 */

/**
 * @param {PublicSuffixes} data
 * @returns {SuffixIndex}
 */
export function indexPublicSuffixes(data) {
  const all = [...data.icann, ...data.private];
  return {
    rules: new Set(all.filter((r) => !r.startsWith("!") && !r.startsWith("*."))),
    wildcards: new Set(all.filter((r) => r.startsWith("*.")).map((r) => r.slice(2))),
    exceptions: new Set(all.filter((r) => r.startsWith("!")).map((r) => r.slice(1))),
    privateRules: new Set(data.private),
  };
}

/**
 * @typedef {object} Registrable
 * @property {string} domain  the suffix plus one label, e.g. "example.co.jp", "tenant.vercel.app"
 * @property {string} suffix
 * @property {boolean} shared  the suffix is a shared host's (the PSL's PRIVATE section)
 */

/**
 * The PSL algorithm: the longest matching rule wins, an exception rule shortens a wildcard by one label, and an
 * unlisted top-level label is its own suffix.
 * @param {string} host
 * @param {SuffixIndex} index
 * @returns {Registrable | null}  null when the host is itself a public suffix
 */
export function registrable(host, index) {
  const name = host.toLowerCase().replace(/\.$/, "");
  // An IP address has no suffix: it is its own site, and "the last two numbers" say nothing about who runs it.
  if (IPV4.test(name) || name.startsWith("[")) return { domain: name, suffix: "", shared: false };
  const labels = name.split(".");
  const match = longestSuffix(labels, index);
  if (labels.length <= match.length) return null;
  const suffix = labels.slice(-match.length).join(".");
  return { domain: labels.slice(-(match.length + 1)).join("."), suffix, shared: index.privateRules.has(match.rule) };
}

/**
 * @param {string[]} labels
 * @param {SuffixIndex} index
 * @returns {{ length: number, rule: string }}  how many trailing labels form the public suffix, and the rule that won
 */
function longestSuffix(labels, index) {
  for (let i = 0; i < labels.length; i++) {
    const candidate = labels.slice(i).join(".");
    const parent = labels.slice(i + 1).join(".");
    if (index.exceptions.has(candidate)) return { length: labels.length - i - 1, rule: `!${candidate}` };
    if (index.rules.has(candidate)) return { length: labels.length - i, rule: candidate };
    if (index.wildcards.has(parent)) return { length: labels.length - i, rule: `*.${parent}` };
  }
  return { length: 1, rule: "*" };
}
