// Registrable domains from the bundled Public Suffix List: the part of a hostname one organisation (or one
// customer of a shared host) controls.

/**
 * @typedef {object} PublicSuffixes  as generated by tools/update-data.mjs
 * @property {string[]} icann
 * @property {string[]} private
 */

/**
 * @typedef {object} SuffixIndex
 * @property {Set<string>} rules
 * @property {Set<string>} wildcards  parents of "*." rules
 * @property {Set<string>} exceptions
 * @property {Set<string>} privateSuffixes  every rule of the PRIVATE section, without its prefix
 */

/**
 * @param {PublicSuffixes} data
 * @returns {SuffixIndex}
 */
export function indexPublicSuffixes(data) {
  const all = [...data.icann, ...data.private];
  return {
    rules: new Set(all.filter((r) => !r.startsWith("!") && !r.startsWith("*."))),
    wildcards: new Set(all.filter((r) => r.startsWith("*.")).map((r) => r.slice(2))),
    exceptions: new Set(all.filter((r) => r.startsWith("!")).map((r) => r.slice(1))),
    privateSuffixes: new Set(data.private.map((r) => r.replace(/^(?:!|\*\.)/, ""))),
  };
}

/**
 * @typedef {object} Registrable
 * @property {string} domain  the suffix plus one label, e.g. "example.co.jp", "tenant.vercel.app"
 * @property {string} suffix
 * @property {boolean} shared  the suffix is a shared host's (the PSL's PRIVATE section)
 */

/**
 * The PSL algorithm: the longest matching rule wins, an exception rule shortens a wildcard by one label, and an
 * unlisted top-level label is its own suffix.
 * @param {string} host
 * @param {SuffixIndex} index
 * @returns {Registrable | null}  null when the host is itself a public suffix
 */
export function registrable(host, index) {
  const labels = host.toLowerCase().replace(/\.$/, "").split(".");
  const suffixLength = longestSuffix(labels, index);
  if (labels.length <= suffixLength) return null;
  const suffix = labels.slice(-suffixLength).join(".");
  return { domain: labels.slice(-(suffixLength + 1)).join("."), suffix, shared: index.privateSuffixes.has(suffix) };
}

/**
 * @param {string[]} labels
 * @param {SuffixIndex} index
 * @returns {number}  how many trailing labels form the public suffix
 */
function longestSuffix(labels, index) {
  for (let i = 0; i < labels.length; i++) {
    const candidate = labels.slice(i).join(".");
    if (index.exceptions.has(candidate)) return labels.length - i - 1;
    if (index.rules.has(candidate) || index.wildcards.has(labels.slice(i + 1).join("."))) return labels.length - i;
  }
  return 1;
}
